global:
  scrape_interval: 15s # How often to pull data
  evaluation_interval: 15s # How often to evaluate rules

rule_files:
  - "rules.yml"  # <--- Add this line

scrape_configs:
  # Job 1: Prometheus monitoring itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    static_configs:
      # Use container name 'node-exporter'
      - targets: ['node-exporter:9100'] 

  - job_name: 'cadvisor'
    static_configs:
      # Use container name 'cadvisor'
      - targets: ['cadvisor:8081']
  
  - job_name: 'ai_service'
    scrape_interval: 5s # Scrape faster for testing
    static_configs:
      - targets: ['ai-service:8000']

  - job_name: 'ollama_exporter'
    static_configs:
      - targets: ['ollama-exporter:9877']

  - job_name: 'weaviate'
    scrape_interval: 10s
    static_configs:
      - targets: ['weaviate:2112']